plugins:
  - jekyll-feed
  - jekyll-paginate

# Conversion
markdown:    kramdown
highlighter: rouge

# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

defaults:
  # Blog post permalinks
  - scope:
      path: "_posts"
      type: posts
    values:
      permalink: /blog/:categories/:title


# Pagination for blog page
paginate: 5
paginate_path: "/blog/page:num/"